### ISSUE TITLE
Script d'installation ajoute la ligne dans le bashrc sans verifier si deja la

### ISSUE THREAD

**Issue by MaDumont** [clubcapra/Takin#33]
À chaque execution du script d'installation, cette ligne est ajouté à la fin du document sans vérifier si elle est déjà présente.

source /opt/ros/kinetic/setup.bash

Ça peut créer des problèmes.

**Comment by LazyEngineerToBe** [comment]
@island212 Je crois que tu as corrigé ce problème lors de ton dernier commit. Est-ce qu'on peut fermer ce issue?

**Comment by island212** [comment]
@LazyEngineerToBe Oui. Je vais fermer l'issue
