### ISSUE TITLE
Publish estop status

### ISSUE THREAD

**Issue by LazyEngineerToBe** [clubcapra/takin#73]
Feedback is required in the UI.

## Suggested solution
Adding a publisher for the estop status.

### First implementation
Publish the output pin status.

### Best implementation
Publish the input pin status. (Requires a new pcb with a feedback pin.)

**Comment by Ludoenso** [comment]
If you don't mind, you could remove the commented section `COMMENTED FOR REFERENCES PURPOSES`, it was just to make sure we don't lose anything while doing the competition, but since we don't have any issue with it, it's not necessary to keep it. If you don't want to do it, that's ok.

**Comment by LazyEngineerToBe** [comment]
Je l'avais laissé ouvert à cause de la section best implementation. Je sais pas trop comment tu veux gérer ça

**Comment by Ludoenso** [comment]
Oh sorry! Though since it was merged it was done. It's confusing me, maybe we should create 2 issues for this instead.

**Comment by LazyEngineerToBe** [comment]
You're right, let's create another issue and close this one.
