### ISSUE TITLE
Implement ros_control

### ISSUE THREAD

**Issue by LazyEngineerToBe** [clubcapra/takin#75]
- [x] talonSRX_hardware_interface 
    - [ ] Communicate with CTRE API
    - [ ] Support encoder
- [x] add flippers_controller
    - [ ] Axe limit
- [x] diff_drive_controller config
- [x] Test in simulation
- [ ] Test on the robot
- [ ] Add flipper hardware interface object inside base node

**Comment by lvanasse** [comment]
- [x] takin_control
- [x] talonSRX_hardware_interface
- [x] diff_drive_controller config
- [ ] flipper_controller config
- [ ] control individual flipper (position and velocity)

We might need to do the URDF for the controller.

**Comment by lit-af** [comment]
There's an URDF of Takin in [takin_sim](https://github.com/clubcapra/takin_sim)

**Comment by lvanasse** [comment]
http://wiki.ros.org/ros_control/Tutorials/Create%20your%20own%20hardware%20interface

**Comment by lvanasse** [comment]
https://github.com/ros-controls/ros_control/wiki/Writing-CombinedRobotHW

**Comment by lit-af** [comment]
Serait intéressant de jeter un coup d'oeil à https://github.com/tu-darmstadt-ros-pkg/hector_tracked_vehicles_common/tree/master/hector_tracked_vehicles_flipper_controller

**Comment by lvanasse** [comment]
https://slaterobots.com/blog/5abd8a1ed4442a651de5cb5b/how-to-implement-ros_control-on-a-custom-robot

**Comment by lvanasse** [comment]
Successfully configure the ros_control setup! Only needs to add the integration with the CTRE motors and integration inside the simulation.
