### ISSUE TITLE
At boot launch the takin_web_ui.launch file on the Jetson TX2

### ISSUE THREAD

**Issue by LazyEngineerToBe** [clubcapra/takin#76]
a bash script called by the rc.local should be enough.
`source Code/takin/devel/setup.bash`
`roslaunch takin_bringup takin_web_ui.launch`

**Comment by lit-af** [comment]
@CloeD Est-ce que cette tâche là est réellement terminé?

**Comment by CloeD** [comment]
Yes ! On l'a vérifié et revérifié

**Comment by lit-af** [comment]
@island212 Faudrait que le code soit push sur github. Soit dans capra_toolbox ou dans takin.

**Comment by lvanasse** [comment]
I think we could add the `rc.local` file inside `takin` repository. We could add a `takin_config` folder.

**Comment by lit-af** [comment]
@Ludoenso We should put it in this folder or even in the same file. https://github.com/clubcapra/takin/blob/master/takin_bringup/config/init.sh

**Comment by lvanasse** [comment]
Yes, that would be best.
