### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Ludoenso** [clubcapra/takin#79]
Update the README with specifications for the repo. Something similar to capra_web_ui repo.

**Comment by Ludoenso** [comment]
- Added ROS version
- How to download the deps 
- How to compile
- What to execute
- Debug section

**Comment by lit-af** [comment]
@Ludoenso Should this issue be closed or do you prefer to keep it open?

**Comment by lvanasse** [comment]
We'll reopen it when we think we should update the ReadMe, else will just forget about it. Constant reminder tends to be forgotten.
