### ISSUE TITLE
Integrate Camera Embedded S

### ISSUE THREAD

**Issue by island212** [clubcapra/Takin#83]
Implement and Integrate the Camera Embedded S on the Jetson Xavier
- [ ] Integrate on Jetson Xavier
- [x] Documentation
- [x] Publish color image
- [x] Publish depth image

**Comment by lit-af** [comment]
This package [ros_astra_camera](https://github.com/orbbec/ros_astra_camera) works with the camera. The only issue encountered is that the color image is published as a grey image.

**Comment by lvanasse** [comment]
It would be wise to test the [ros_astra_camera](https://github.com/orbbec/ros_astra_camera) with the Astra Mini that we currently have inside Takin robot. 

If that proves to be successful, we could change the submodules inside [takin](https://github.com/clubcapra/takin) for the Orbbec's ones and remove the [ros_astra_camera](https://github.com/clubcapra/ros_astra_camera) and the [ros_astra_launch](https://github.com/clubcapra/ros_astra_launch) forks that we have.

**Comment by lit-af** [comment]
> This package [ros_astra_camera](https://github.com/orbbec/ros_astra_camera) works with the camera. The only issue encountered is that the color image is published as a grey image.

Tested again today. The issue wasn't replicable. 
`roslaunch astra_camera embedded_s.launch`
